### ISSUE TITLE
Build not found

### ISSUE THREAD

**Issue by PittacusOfLorien** [lineageos4microg/l4m_website#26]
I could not find the beryllium build on your official download page. I believe LineageOS just recently implemented it.

**Comment by mawed** [comment]
I'm sorry I have to comment on this closed issue, but I found no other information or a place to ask a question. I also do not know why this Issue was closed without any reaction.

My question:

Is there an estimation, when the berylium-build with microg will be available?

There is an official support with LineageOS 16 now:
https://lineageos.org/Changelog-22/
