### ISSUE TITLE
PlayMaker demo repository not available 

### ISSUE THREAD

**Issue by rugk** [lineageos4microg/l4m_website#5]
> If you don't want to enable "Unknown sources" you can also import the PlayMaker demo repository in F-Droid (by adding this URL to F-Droid) and download it from there.

Unfortunately all things on https://nomore.ovh/fdroid currently just show 404 errors.

**Comment by NoMore201** [comment]
Updated and restarted, sorry for the downtime

**Comment by rugk** [comment]
https://nomore.ovh/fdroid
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1488, in _execute
    result = self.prepare()
  File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 2223, in prepare
    raise HTTPError(self._status_code)
tornado.web.HTTPError: HTTP 404: Not Found
```

Also BTW, is is not a good idea to show a whole traceback (or, in general, too detailed information) in case of a server error.

**Comment by NoMore201** [comment]
Tornado static file handler has no autoindex feature, meaning that if you visit https://nomore.ovh/fdroid you will get an error rather than a list of the file in the repo. To check if is up and running, try to fetch the main repository index:

https://nomore.ovh/fdroid/index.xml

As for the traceback, I pushed a fix to the dev branch, it should be fixed in next release.

**Comment by rugk** [comment]
Ah, okay, thanks.
