### ISSUE TITLE
Pixel 4a builds far behind

### ISSUE THREAD

**Issue by awfm9** [lineageos4microg/l4m_website#79]
Thank you for the amazing project; thanks to you, I'm finally completely free of Google services, including my phone.

I noticed that the builds for the Google Pixel 4a (`sunfish`) have fallen behind quite a bit. The last official LineageOS builds are 20th of May, 27th of May, 3rd of June and 10th of June. The builds for LineageOS for microG are 4th of April and 12 of April.

I've read in a few other issues that you don't have the necessary build resources to keep up. Is there something I could do that would help you guys to keep up?

**Comment by 4n0nym0u53** [comment]
I've got the same concern about the OnePlus 8T. The last update for L4M was pushed at May 8th, while upstream LOS was last updated at June 10th.

**Comment by bananer** [comment]
Trying to keep all discussion around new builds in here: https://github.com/lineageos4microg/docker-lineage-cicd/issues/166

**Comment by henrypp** [comment]
why ouneplus 8t (kebab) is not updated?

**Comment by henrypp** [comment]
same for oneplus 6

**Comment by henrypp** [comment]
@petefoth wtf? last 2 messages

**Comment by petefoth** [comment]
> why oneplus 8t ([kebab](https://download.lineage.microg.org/kebab/)) is not updated?

Because when April's build run started it was [not on the LineageOS build target list](https://github.com/LineageOS/hudson/commit/f4adb0c30793cba4118a020c161bd435b4551669) because lineage-21.0 builds were broken for all devices - see [here](https://github.com/lineageos4microg/docker-lineage-cicd/issues/592#issuecomment-2022099925) and [here](https://xdaforums.com/t/lineageos-for-microg.3700997/page-152#post-89416684).

> @petefoth wtf? (last 2 messages)

If you want / expect a reply, then please don't post comments in old issues what were closed nearly three years ago. Raise a new issue - or, better read the current open issues - or read then post in the [XDA Forum thread](https://xdaforums.com/t/lineageos-for-microg.3700997/)

And if you want a civil response, then please don't tag me saying 'What the fuck?'

**Comment by henrypp** [comment]
@petefoth ok, thx for answer, but 21 qpr was already done, and official builds are [succesfully made](https://download.lineageos.org/devices/kebab/builds) for all official devices, but u are not answer why microg is still not?

**Comment by petefoth** [comment]
> why microg is still not?

LineageOS have the resources to build continuously, we do not. We do one build run per month, building for whatever devices are in the LineageOS build target list ***on the day we start the build run*** usually the 1st of the month. On the April 1st there were no 21.0 devices in that list, and kebab was not enabled  - see https://github.com/LineageOS/hudson/blame/8efa88c868b1d69f5a0f69652231358be541bb8b/lineage-build-targets#L65  so we didn't build for it

In May we will build for whatever devices are in the target list on May 1st. At the moment `kebab` is there, so, unless that changes we will build it some time in May

Looking this issue now as you are ignoring my request not to post in old closed thread.
